[[tls.certificates]]
  certFile = "/certs/k8s.local+4.pem"
  keyFile = "/certs/k8s.local+4-key.pem"

[tls.stores]
  [tls.stores.default]
    [tls.stores.default.defaultCertificate]
      certFile = "/certs/k8s.local+4.pem"
      keyFile = "/certs/k8s.local+4-key.pem"